### ISSUE TITLE
Feedstock creation is failing

### ISSUE THREAD

**Issue by xhochy** [conda-forge/staged-recipes#10667]
Error in Travis is:

```
Adding in variants from /home/travis/build/conda-forge/staged-recipes/conda_build_config.yaml
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 546, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 167, in __call__
    github.create_github_repo(args)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/github.py", line 111, in create_github_repo
    trim_skip=False,
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 45, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 819, in render_recipe
    allow_no_other_outputs=True, bypass_env_check=bypass_env_check)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_build/render.py", line 725, in distribute_variants
    bypass_env_check=bypass_env_check)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 1018, in parse_until_resolved
    bypass_env_check=bypass_env_check)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 940, in parse_again
    bypass_env_check=bypass_env_check),
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_build/metadata.py", line 1528, in _get_contents
    rendered = template.render(environment=env)
  File "/home/travis/miniconda/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/travis/miniconda/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/travis/miniconda/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/travis/miniconda/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/tmp/tmpjptgbzy6__feedstocks/intel_repack-feedstock/recipe/meta.yaml", line 21, in top-level template code
    folder: mkl-devel
TypeError: argument of type 'StrictUndefined' is not iterable
```

**Comment by scopatz** [comment]
Hmm strange, ping @isuruf @conda-forge/core @conda-forge/staged-recipes

**Comment by beckermr** [comment]
See my PR here: https://github.com/conda-forge/staged-recipes/pull/10670

**Comment by beckermr** [comment]
I think we are unblocked, but out of API requests. We'll have to wait and see.

**Comment by beckermr** [comment]
closing since now it is backed up on github api reqeusts

**Comment by jakirkham** [comment]
I prodded some of these through. Would help to get the auto-rebuild script back online so that Travis CI can continue slogging through them for us. ( https://github.com/conda-forge/staged-recipes/pull/10674 )
