### ISSUE TITLE
BUG import error and failing builds

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#10874]
It has been about 20 hours since we have merged a recipe. 

We are seeing an import error [here](https://travis-ci.com/conda-forge/staged-recipes/builds/149370453#L1020)

```
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 191, in <module>
    from conda_smithy.ci_register import drone_sync
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 7, in <module>
    from . import github
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/github.py", line 4, in <module>
    from git import Repo
  File "/home/travis/miniconda/lib/python3.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/travis/miniconda/lib/python3.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/home/travis/miniconda/lib/python3.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

**Comment by beckermr** [comment]
cc @conda-forge/core @conda-forge/staged-recipes

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by beckermr** [comment]
grrr - conda-forge has 3.0.8 but the install is not pulling it

**Comment by Harmon758** [comment]
I think it was only uploaded a couple hours ago.
https://anaconda.org/conda-forge/gitpython/
https://github.com/conda-forge/gitpython-feedstock/pull/36

**Comment by beckermr** [comment]
Yep but it should have found it. In any case, I have now put the constraint in the CI build and things are working. 

Thank you @Harmon758!
