### ISSUE TITLE
Conversion failure (due to AppVeyor API issues)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1198]
Appears we had a conversion failure due to issue registering on AppVeyor. Restarting to see if it clears. Log snippet of the failure below.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/autograd-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
 * conda-forge/autograd-feedstock enabled on CircleCI
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmppra9n4ar__feedstocks/autograd-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Restarting fixed it.

**Comment by jakirkham** [comment]
Seems this happened in another case. Snippet of the error below. Will again try restarting.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/exec-wrappers-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
 * conda-forge/exec-wrappers-feedstock enabled on CircleCI
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpyzc3ve1l__feedstocks/exec-wrappers-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Restarting fixed the issue.

**Comment by jakirkham** [comment]
Failed again on AppVeyor. Re-opening and restarting to see if that fixes the issue. Snippet of the error from the log below.

```
CI support files regenerated. These need to be pushed to github!
[master d1cf90d] Re-render the feedstock after CI registration.
 3 files changed, 12 insertions(+), 1 deletion(-)
 rewrite conda-forge.yml (100%)
rm 'recipes/dodgy/meta.yaml'
CI Summary for conda-forge/lazy_object_proxy-feedstock (can take ~30s):
 * Registered on travis-ci
 * conda-forge/lazy_object_proxy-feedstock enabled on CircleCI
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp1x1spe32__feedstocks/lazy_object_proxy-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
Hmm...same failure it seems. 😕

**Comment by jakirkham** [comment]
Removal of the converted recipe was enough to clear this. Though this doesn't really expose the underlying issue. Closing in any event.
