### ISSUE TITLE
Improve error message when hitting rate-limiting on Travis

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/staged-recipes#13021]
When hitting rate-limiting you currently get a fairly non-informative error:
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url
```
It would be good if some more context could be provided to help users understand the cause.

e.g. (from https://github.com/conda-forge/staged-recipes/pull/13016)
```
+++set +x
+++python .travis_scripts/trigger_travis_build.py conda-forge/staged-recipes
b'access denied'
Traceback (most recent call last):
  File ".travis_scripts/trigger_travis_build.py", line 54, in <module>
    sys.exit(main(sys.argv))
  File ".travis_scripts/trigger_travis_build.py", line 47, in main
    rebuild_travis(args.slug)
  File ".travis_scripts/trigger_travis_build.py", line 38, in rebuild_travis
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.com/repo/conda-forge%2Fstaged-recipes/requests
```

**Comment by isuruf** [comment]
Moved to staged-recipes where this script is located.

**Comment by chrisburr** [comment]
This script doesn't exist now the CI has been moved to GitHub actions so I guess this can be closed.
