### ISSUE TITLE
mplhep_data stuck in staged-recipes

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#14480]
It looks like [the `mplhep_data` recipe]( https://github.com/conda-forge/staged-recipes/blob/c4dbd6b7b487d64fb6956788d765198867e6fa64/recipes/mplhep_data/meta.yaml ) is stuck in `staged-recipes`. Here's [a recent log]( https://github.com/conda-forge/staged-recipes/runs/2283253639?check_suite_focus=true )

cc @conda-forge/staged-recipes @conda-forge/core

**Comment by xhochy** [comment]
CircleCI creation fails for it:

```
2021-04-07T11:41:23.3497802Z CI Summary for conda-forge/mplhep_data-feedstock (can take ~30s):
2021-04-07T11:41:28.0094730Z Traceback (most recent call last):
2021-04-07T11:41:28.0096549Z   File "/home/runner/miniconda/bin/conda-smithy", line 10, in <module>
2021-04-07T11:41:28.0097515Z     sys.exit(main())
2021-04-07T11:41:28.0098765Z   File "/home/runner/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 613, in main
2021-04-07T11:41:28.0099805Z     args.subcommand_func(args)
2021-04-07T11:41:28.0101065Z   File "/home/runner/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 265, in __call__
2021-04-07T11:41:28.0102156Z     ci_register.add_project_to_circle(owner, repo)
2021-04-07T11:41:28.0103833Z   File "/home/runner/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 204, in add_project_to_circle
2021-04-07T11:41:28.0105017Z     response.raise_for_status()
2021-04-07T11:41:28.0106342Z   File "/home/runner/miniconda/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
2021-04-07T11:41:28.0107515Z     raise HTTPError(http_error_msg, response=self)
2021-04-07T11:41:28.0110327Z requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://circleci.com/api/v1.1/project/github/conda-forge/mplhep_data-feedstock/follow?circle-token=***
2021-04-07T11:41:28.0995637Z Traceback (most recent call last):
2021-04-07T11:41:28.0996892Z   File ".travis_scripts/create_feedstocks.py", line 269, in <module>
2021-04-07T11:41:28.0997798Z     feedstock_dir] + owner_info)
2021-04-07T11:41:28.1000627Z   File "/home/runner/miniconda/lib/python3.7/subprocess.py", line 341, in check_call
2021-04-07T11:41:28.1002624Z     raise CalledProcessError(retcode, cmd)
2021-04-07T11:41:28.1005408Z subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--without-appveyor', '--without-webservice', '--feedstock_directory', '/tmp/tmplc204p0n__feedstocks/mplhep_data-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1.
2021-04-07T11:41:28.1396140Z No local changes to save
```

**Comment by beckermr** [comment]
Yup. I just deleted the repo and stopped building the project on circle. Let's try again.

**Comment by beckermr** [comment]
This cleared it! Closing!

**Comment by jakirkham** [comment]
Thanks all! 😀
