### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#1682]
Interesting issue to keep an eye on.

``` python
Repository created, please edit conda-forge.yml to configure the upload channels
and afterwards call 'conda smithy register-github'
CI Summary for conda-forge/petl-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy==1.2.0', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 159, in __call__
    ci_register.travis_token_update_conda_forge_config(args.feedstock_directory, owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 226, in travis_token_update_conda_forge_config
    travis_encrypt_binstar_token(slug, item)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 253, in travis_encrypt_binstar_token
    r.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.travis-ci.org/repos/conda-forge/petl-feedstock/key
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 185, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpwsvahz88__feedstocks/petl-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
FYI restarting made this go away, but maybe there is some subtle timing issue.

**Comment by jakirkham** [comment]
Haven't seen this in a while. Going to close it out.
