### ISSUE TITLE
tkinter package in linux_64 docker machine

### ISSUE THREAD

**Issue by GurjeetSinghSangra** [conda-forge/staged-recipes#22138]
### Bug:

please ping conda-forge/staged-recipes

I made a PR for releasing a Python package at the following [PR 22131](https://github.com/conda-forge/staged-recipes/pull/22131).
One systematic test is failing on Linux os\_64.  Instead, tests are all passed on `mac_os` and `windows` machines.
The systematic check fails on Linux when importing the releasing package, but the error is due to the  [tkinter](https://docs.python.org/3/library/tkinter.html#module-tkinter) missing package, which should be included in the standard python package, and no explicit imports are actually done in our source code.
`import _tkinter # If this fails your Python may not be configured for Tk`
This error arises just on the Linux docker machine. I tried several times re-launching the tests, but it keeps failing.
Can you help me, please?

The full stack trace is:
```
import: 'pybads' 
Traceback (most recent call last): 
 File "/home/conda/staged-recipes/build_artifacts/pybads_1677254096967/test_tmp/run_test.py", line 2, in <module> 
 import pybads 
 File "/home/conda/staged-recipes/build_artifacts/pybads_1677254096967/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pybads/__init__.py", line 2, in <module> 
 import pybads.bads 
 File "/home/conda/staged-recipes/build_artifacts/pybads_1677254096967/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pybads/bads/__init__.py", line 4, in <module> 

 from .bads import BADS 

 File "/home/conda/staged-recipes/build_artifacts/pybads_1677254096967/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pybads/bads/bads.py", line 24, in <module> 

 from .gaussian_process_train import ( 

 File "/home/conda/staged-recipes/build_artifacts/pybads_1677254096967/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pybads/bads/gaussian_process_train.py", line 6, in <module> 

 from turtle import width 

 File "/home/conda/staged-recipes/build_artifacts/pybads_1677254096967/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/turtle.py", line 107, in <module> 

 import tkinter as TK 

 File "/home/conda/staged-recipes/build_artifacts/pybads_1677254096967/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/tkinter/__init__.py", line 38, in <module> 

 import _tkinter # If this fails your Python may not be configured for Tk
```

**Comment by GurjeetSinghSangra** [comment]
please ping conda-forge/staged-recipes

**Comment by GurjeetSinghSangra** [comment]
@conda-forge-admin, please ping conda-forge/staged-recipes

**Comment by GurjeetSinghSangra** [comment]
Solved. It was a wrong issue, the bug was not from this repository.
