### ISSUE TITLE
New feedstock(s) creation failing with "RuntimeError: Unable to retrieve repo info from Travis" error

### ISSUE THREAD

**Issue by traversaro** [conda-forge/staged-recipes#24406]
### Bug:

I noticed that no recipe was being generated for https://github.com/conda-forge/staged-recipes/pull/23226 . Furthermore, this seems to be happening for many recipes. I checked the job for creating feedstocks at https://github.com/conda-forge/admin-requests/actions/workflows/create_feedstocks.yml and the log seems: 

~~~
2023-11-02T07:52:56.1232334Z Making feedstock for distrax
2023-11-02T07:52:57.0615805Z WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
2023-11-02T07:52:57.0812880Z Initialized empty Git repository in /tmp/tmprmpby9fq__feedstocks/distrax-feedstock/.git/
2023-11-02T07:52:57.0913959Z [main (root-commit) 2e8814d] Initial feedstock commit with conda-smithy 3.27.1.
2023-11-02T07:52:57.0914958Z  3 files changed, 58 insertions(+)
2023-11-02T07:52:57.0915597Z  create mode 100644 conda-forge.yml
2023-11-02T07:52:57.0916354Z  create mode 100644 recipe/01-exclude-examples.patch
2023-11-02T07:52:57.0917054Z  create mode 100644 recipe/meta.yaml
2023-11-02T07:52:57.0945902Z 
2023-11-02T07:52:57.0947056Z Repository created, please edit conda-forge.yml to configure the upload channels
2023-11-02T07:52:57.0948543Z and afterwards call 'conda smithy register-github'
2023-11-02T07:52:58.0711653Z fatal: 'upstream_with_token/main' is not a commit and a branch 'main' cannot be created from it
2023-11-02T07:52:58.0738576Z Switched to a new branch 'main'
2023-11-02T07:52:59.0341260Z WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
2023-11-02T07:52:59.1038716Z Adding in variants from internal_defaults
2023-11-02T07:52:59.6817148Z Github repository already exists.
2023-11-02T07:52:59.6894897Z 
2023-11-02T07:52:59.6895940Z Repository registered at github, now call 'conda smithy register-ci'
2023-11-02T07:52:59.9280204Z 
2023-11-02T07:52:59.9281571Z GitHub API Rate Limit Info:
2023-11-02T07:52:59.9282893Z ---------------------------
2023-11-02T07:52:59.9283733Z token:  GH_TOKEN
2023-11-02T07:52:59.9284550Z Currently remaining 4788 out of 5000.
2023-11-02T07:52:59.9285574Z Will reset in 0:47:54.072313.
2023-11-02T07:52:59.9286199Z 
~~~

Indeed, the feedstock repo was created but not populated: https://github.com/conda-forge/distrax-feedstock .

Interestingly, instead the creation went fine for some feedstocks (https://github.com/conda-forge/staged-recipes/commit/c7f5f26c72cc17ee436868f241401e71844fe266), not sure what is the difference with all the other repos.

fyi @conda-forge/staged-recipes @flferretti

**Comment by traversaro** [comment]
This seems a similar failure: https://github.com/conda-forge/staged-recipes/issues/2311 .

**Comment by jakirkham** [comment]
cc @conda-forge/core (for awareness)

**Comment by jakirkham** [comment]
Think the error above isn't the actual cause. Instead there are errors later in the log related to Travis CI registration issues. For example

```python
CI Summary for conda-forge/pypromice-feedstock (can take ~30s):
404 Client Error: Not Found for url: https://api.travis-ci.com/repo/conda-forge%2Fpypromice-feedstock
Traceback (most recent call last):
  File "/home/runner/Mambaforge/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/runner/Mambaforge/lib/python3.10/site-packages/conda_smithy/cli.py", line 625, in main
    args.subcommand_func(args)
  File "/home/runner/Mambaforge/lib/python3.10/site-packages/conda_smithy/cli.py", line 295, in __call__
    ci_register.travis_configure(owner, repo)
  File "/home/runner/Mambaforge/lib/python3.10/site-packages/conda_smithy/ci_register.py", line 482, in travis_configure
    raise RuntimeError(msg.format(user, project))
RuntimeError: Unable to retrieve repo info from Travis
(Is it down? Is the "conda-forge/pypromice-feedstock" name spelt correctly? [note: case sensitive])
Traceback (most recent call last):

  File "/home/runner/work/admin-requests/admin-requests/.github/workflows/scripts/create_feedstocks.py", line 350, in <module>
    subprocess.check_call(
  File "/home/runner/Mambaforge/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--without-appveyor', '--without-circle', '--without-drone', '--without-webservice', '--feedstock_directory', '/tmp/tmpzc75hkz4__feedstocks/pypromice-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1.
```

Have just picked the one I saw, but this pattern occurs for all recipes in `staged-recipes`

**Comment by traversaro** [comment]
> Think the error above isn't the actual cause. Instead there are errors later in the log related to Travis CI registration issues. For example

Thanks, I edited the title.

**Comment by traversaro** [comment]
I am not sure what changed, but now all the recipe were created, see https://github.com/conda-forge/staged-recipes/commit/b309b63fd77b38488ac685b4d48cf902b3548811 (except for pypromice that I guess has some indipendent problem).

**Comment by traversaro** [comment]
I think I can close the issue, if anyone thinks otherwise feel free to comment.

**Comment by jakirkham** [comment]
There was still one recipe that wasn't being converted `pypromice` as noted in this comment ( https://github.com/conda-forge/admin-requests/issues/855#issuecomment-1794710962 ). While it didn't clear with the rest, it cleared recently ( https://github.com/conda-forge/staged-recipes/commit/420c25db7de4fa02d938db32e3f08c207607fc5d ). So think we can mark this resolved now

cc @ocefpaf (for awareness)

**Comment by ocefpaf** [comment]
I deleted the partial feedstock and restarted the job. That "fixed" pypromice BTW.

**Comment by jakirkham** [comment]
Ah was thinking about doing the same

Though was already on a thread with Travis where they applied a fix that helped the rest. So thought they might want to try something else

Deleting probably allowed the same fix Travis deployed to be applied to `pypromice`
