### ISSUE TITLE
The release of optuna v3.6.1 did not work

### ISSUE THREAD

**Issue by HideakiImamura** [conda-forge/staged-recipes#26577]
### General comment:

Hello @conda-forge/staged-recipes

I'm one of the maintainer of https://github.com/conda-forge/optuna-feedstock. Recently, optuna v3.6.1 has been released and the PR https://github.com/conda-forge/optuna-feedstock/pull/64 has been merged. However, it seems that the build of optuna v3.6.1 failed [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=908936&view=results). Could you give me any instructions to release the v3.6.1 appropriately?

**Comment by ocefpaf** [comment]
Please don't open issue on staged-recipes for a problem in the feedstock. You can ping the for help in an issue there. Also, don't ping the stage-recipes team b/c they handle reviews here. You can ping the core for issues that are infrastructure related. With all that said, you log says:

```
Failed to upload due to ('?: Undefined error ([GET] https://api.anaconda.org/dist/conda-forge/optuna/3.6.1/noarch/optuna-3.6.1-pyhd8ed1ab_0.tar.bz2 -> 524)', 524). Trying again in 87.96388244628906 seconds
Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
INFO:binstar:Using Anaconda API: https://api.anaconda.org/

  0%|          | 0.00/218k [00:00<?, ?B/s]
  7%|▋         | 16.0k/218k [00:00<00:01, 158kB/s]
223kB [00:00, 660kB/s]                            
ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
copy results:
{}
Failed to upload due to copy from staging to production channel failed. Trying again in 153.93679428100586 seconds
Traceback (most recent call last):
  File "/opt/conda/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 248, in upload_package
    retry_upload_or_check(
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 322, in retry_upload_or_check
    raise TimeoutError("Did not manage to upload package.  Failing.")
TimeoutError: Did not manage to upload package.  Failing.
```

That is a temporary network issue and a job restart should fix it. If you cannot restart the CIs you can always send a fresh PR with an empty commit. I am restarting it for you though.
