### ISSUE TITLE
`build-locally.py` fails on import `HashableDict`

### ISSUE THREAD

**Issue by MementoRC** [conda-forge/staged-recipes#27154]
### Bug:

```
Building all recipes
+ python /home/conda/staged-recipes-copy/.ci_support/build_all.py
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 7, in <module>
    from compute_build_graph import construct_graph
  File "/home/conda/staged-recipes-copy/.ci_support/compute_build_graph.py", line 49, in <module>
    from conda_build.utils import HashableDict
ImportError: cannot import name 'HashableDict' from 'conda_build.utils' (/opt/conda/lib/python3.10/site-packages/conda_build/utils.py)
Traceback (most recent call last):
  File "/unsecured_home/memento/PycharmP/staged-recipes/build-locally.py", line 101, in <module>
    main()
  File "/unsecured_home/memento/PycharmP/staged-recipes/build-locally.py", line 95, in main
    run_docker_build(ns)
  File "/unsecured_home/memento/PycharmP/staged-recipes/build-locally.py", line 33, in run_docker_build
    subprocess.check_call([script])
  File "/home/memento/.conda/envs/python-3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```

**Comment by MementoRC** [comment]
It looks like it has been deprecated:
   https://github.com/conda/conda-build/releases/tag/24.7.0

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/staged-recipes/pull/27151
