### ISSUE TITLE
Recipes failing on master branch due to JSON encoding 

### ISSUE THREAD

**Issue by rth** [conda-forge/staged-recipes#2735]
A number commits with new recipes  that I believe successfully passed CI test as PRs [failed in the `master` branch](https://github.com/conda-forge/staged-recipes/commits/master).

Here is an example of exception traceback,
```pytb
CI Summary for conda-forge/mu_repo-feedstock (can take ~30s):
 * Registered on travis-ci
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 275, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 160, in __call__
    ci_register.travis_configure(owner, repo)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 281, in travis_configure
    content = response.json()
  File "/Users/travis/miniconda/lib/python2.7/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/travis/miniconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/travis/miniconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/travis/miniconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 195, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpikLqrw__feedstocks/mu_repo-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

not sure how normal that is, couldn't find anything similar in existing issues, so opening a new one in case it might be useful.

**Comment by ericdill** [comment]
It's been happening for a while now. We're tracking it [here](https://github.com/conda-forge/conda-smithy/issues/233), starting to debug it a little bit [here](https://github.com/conda-forge/conda-smithy/pull/498) and thinking about a longer term solution [here](https://github.com/conda-forge/staged-recipes/issues/2619)

**Comment by rth** [comment]
Aww fair enough, I should have searched in the full org not just this repo.. Closing as duplicate.

**Comment by ericdill** [comment]
> I should have searched in the full org not just this repo..

This is turning into quite the sprawling organization. No worries 😀 . It's not always even obvious what to search for
