### ISSUE TITLE
Set `CONDA_NPY` on Linux

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#383]
We still need to set the `CONDA_NPY` dummy environment on Linux. I guess that is because we are still an older conda-build (1.18.2) there.

```shell
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build-all", line 9, in <module>
    load_entry_point('conda-build-all==0.11.0', 'console_scripts', 'conda-build-all')()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/cli.py", line 85, in main
    b.main()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 207, in main
    recipe_metas = self.fetch_all_metas()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 150, in fetch_all_metas
    recipe_metas = sort_dependency_order(recipe_metas)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 97, in sort_dependency_order
    meta.parse_again()
  File "/opt/conda/lib/python3.5/site-packages/conda_build/metadata.py", line 356, in parse_again
    self.meta = parse(self._get_contents(permit_undefined_jinja))
  File "/opt/conda/lib/python3.5/site-packages/conda_build/metadata.py", line 634, in _get_contents
    env.globals.update(context_processor(self, path))
  File "/opt/conda/lib/python3.5/site-packages/conda_build/jinja_context.py", line 65, in context_processor
    ctx = get_environ(m=initial_metadata)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/environ.py", line 248, in get_dict
    d['PKG_BUILD_STRING'] = str(m.build_id())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/metadata.py", line 461, in build_id
    for ms in self.ms_depends():
  File "/opt/conda/lib/python3.5/site-packages/conda_build/metadata.py", line 434, in ms_depends
    ms = handle_config_version(ms, ver)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/metadata.py", line 307, in handle_config_version
    raise RuntimeError("'%s' requires external setting" % ms.spec)
RuntimeError: 'numpy x.x' requires external setting
```

See https://circleci.com/gh/conda-forge/staged-recipes/2056 and https://github.com/conda-forge/staged-recipes/pull/381#discussion_r60034195

Ping @pelson

**Comment by pelson** [comment]
Thanks @ocefpaf. We have the ability to control this through conda-build-all :smile: - I think we can put the fix there. In the meantime :+1: on having a workaround in this repo. :+1:

**Comment by ocefpaf** [comment]
Too old and solved.
