### ISSUE TITLE
local CI build fails witih conda >= 4.3 repodata.json 

### ISSUE THREAD

**Issue by kastman** [conda-forge/staged-recipes#5730]
Looks like there was a change in conda to necessitate repodata.json for local channels, so running the CI locally fails with an invalid channel message. Below is an excerpt of the output, raising the error:

``` bash
+ $.circleci/run_docker_build.sh
+ ... a bunch of truncated output
+ python /home/conda/.ci_support/build_all.py /home/conda/conda-recipes
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 419, in fetch_repodata_remote_request
    resp.raise_for_status()
  File "/opt/conda/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: None for url: file:///home/conda/staged-recipes/build_artifacts/noarch/repodata.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 83, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 35, in build_all
    index = conda_build.conda_interface.get_index(channel_urls=channel_urls)
  File "/opt/conda/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.6/site-packages/conda/core/index.py", line 65, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache)
  File "/opt/conda/lib/python3.6/site-packages/conda/core/index.py", line 83, in fetch_index
    index = collect_all_repodata_as_index(use_cache, channel_urls)
  File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 598, in collect_all_repodata_as_index
    index.update(sd.iter_dists_records())
  File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 164, in iter_dists_records
    self.load()
  File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 148, in load
    _internal_state = self._load()
  File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 216, in _load
    mod_etag_headers.get('_mod'))
  File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 550, in fetch_repodata_remote_request
    caused_by=e)
conda.exceptions.CondaHTTPError: HTTP 404 CONNECTION FAILED for url <file:///home/conda/staged-recipes/build_artifacts/noarch/repodata.json>
Elapsed: 00:00.001186

The remote server could not find the noarch directory for the
requested channel with url: file:///home/conda/staged-recipes/build_artifacts

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.
```

This is running from the condaforge/linux-anvil docker image, so I'm confused about why it hasn't been seen before (it's not a problem with the local conda, for example). What could be unique about my scenario that this isn't getting picked up on the actual circleci? I pulled and based this off of `bd15ae8`, the most recent master. 

Thanks,

**Comment by kastman** [comment]
I suspect this may have to do with running conda-build 2 locally (for compatibility with bioconda's build stack); will update if I figure it out.

**Comment by jakirkham** [comment]
Can you please link the log (if there is one)? Seems cutoff at the top.

**Comment by kastman** [comment]
Got it - for some reason a "build_artifacts" directory was created at the top level, which was somehow messing up the local channel. Very weird but it's not giving me trouble anymore at least. Thank you @jakirkham for taking a glance at least!
