### ISSUE TITLE
r-future.batchtools

### ISSUE THREAD

**Issue by nick-youngblut** [conda-forge/staged-recipes#5758]
This is a request for `r-future.batchtools`. I see that conda-forge [already has a recipe for `r-future`](https://anaconda.org/conda-forge/r-future), but it appears that conda-forge does not have a recipe for `r-future.batchtools`, which thus limits the usefulness of `r-future`. I've tried using `conda skeleton cran` and `conda-build` to build `r-future.batchtools` myself. However, I get the following dependency conflict error:

```
$ conda-build r-future.batchtools/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for r-future.batchtools
INFO:conda_build.metadata:Attempting to finalize metadata for r-future.batchtools
Solving environment: ...working... failed
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Missing dependency r-batchtools, but found recipe directory, so building r-batchtools first
Attempting to finalize metadata for r-batchtools
INFO:conda_build.metadata:Attempting to finalize metadata for r-batchtools
Solving environment: ...working... done
Solving environment: ...working... failed
failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - r-base64url[version='>=1.1']
  - r-checkmate[version='>=1.8.5']
Use "conda info <package>" to see the dependencies for each package.
WARNING:conda_build.environ:failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - r-base64url[version='>=1.1']
  - r-checkmate[version='>=1.8.5']
Use "conda info <package>" to see the dependencies for each package.
Solving environment: ...working... failed
Solving environment: ...working... failed
Solving environment: ...working... failed
Failed to get install actions, max retries exceeded.
ERROR:conda_build.environ:Failed to get install actions, max retries exceeded.
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/environ.py", line 706, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
    force_remove, force_reinstall)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 438, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 331, in solve_final_state
    solution = r.solve(tuple(final_environment_specs))  # return value is List[dist]
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 857, in solve
    self.find_conflicts(specs)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 244, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - r-base64url[version='>=1.1']
  - r-checkmate[version='>=1.8.5']
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/environ.py", line 706, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
    force_remove, force_reinstall)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 438, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 331, in solve_final_state
    solution = r.solve(tuple(final_environment_specs))  # return value is List[dist]
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 857, in solve
    self.find_conflicts(specs)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 244, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - r-base64url[version='>=1.1']
  - r-checkmate[version='>=1.8.5']
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/environ.py", line 706, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
    force_remove, force_reinstall)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 438, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 331, in solve_final_state
    solution = r.solve(tuple(final_environment_specs))  # return value is List[dist]
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 857, in solve
    self.find_conflicts(specs)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 244, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - r-base64url[version='>=1.1']
  - r-checkmate[version='>=1.8.5']
Use "conda info <package>" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/build.py", line 2117, in build_tree
    notest=notest,
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/build.py", line 1169, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/render.py", line 703, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/metadata.py", line 1873, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/metadata.py", line 683, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/render.py", line 494, in finalize_metadata
    exclude_pattern)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/render.py", line 352, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/render.py", line 322, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/render.py", line 125, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/environ.py", line 742, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/environ.py", line 742, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/environ.py", line 742, in get_install_actions
    channel_urls=tuple(channel_urls))
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda_build/environ.py", line 706, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/plan.py", line 541, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
    force_remove, force_reinstall)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 438, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/core/solve.py", line 331, in solve_final_state
    solution = r.solve(tuple(final_environment_specs))  # return value is List[dist]
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 857, in solve
    self.find_conflicts(specs)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/lib/python3.6/site-packages/conda/resolve.py", line 244, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - r-base64url[version='>=1.1']
  - r-checkmate[version='>=1.8.5']
Use "conda info <package>" to see the dependencies for each package.
```

I get this error even if I try to remove the specific version requirements from all of the `meta.yaml` files for `r-future.batchtools` and its dependency packages. I've tried to get help for this issue at  the `conda-build` GitHub repo issues forum, but I haven't gotten any response (it's been a couple of weeks). 

Maybe this dependency conflict is why `r-future.batchtools` isn't already hosted on the conda-forge channel, but I'm hoping that it could be solved so that myself and other researchers can use `conda` + `future` + `batchtools` for running highly paralleled jobs on the compute clusters that we have available.

**Comment by isuruf** [comment]
You need to first make sure the dependencies are there.
`r-base64url` is not packaged yet. Please send a PR to package it.
`r-checkmate` version in conda-forge is old. Please send a PR to https://github.com/conda-forge/r-checkmate-feedstock to update it.
`r-batchtools` is not packaged yet. Please send a PR to package it. This needs to happen after the above 2 tasks are done.
After these, send a PR to package `r-future.batchtools`.

**Comment by nick-youngblut** [comment]
The PR for `r-batchtools` is going to be a problem, because building it with `conda-build` generates the `conda.exceptions.UnsatisfiableError` error as shown above. The issue is really `r-batchtools`, not `r-future.batchtools`. I don't know how do fix the `conda.exceptions.UnsatisfiableError`, so I don't think that I'll be able to create a PR for `r-batchtools`.

**Comment by isuruf** [comment]
> I don't know how do fix the conda.exceptions.UnsatisfiableError

I just told you how to fix it. See point 1 & 2 above

**Comment by nick-youngblut** [comment]
Yeah, you're right. Sorry about that. 

I tried to see if I could build the packages locally before I create the PRs (`r-base64url` & `r-checkmate`, followed by `r-batchtools` and then `r-future.batchtools`). I ran into a problem when trying to build `r-batchtools` during the test of `r-batchtools`:

```
## Package Plan ##

  environment location: /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/r-batchtools_1525026363975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-1              conda-forge
    ca-certificates: 2018.4.16-0          conda-forge
    cairo:           1.14.6-4             conda-forge
    curl:            7.54.1-0             conda-forge
    fontconfig:      2.12.1-6             conda-forge
    freetype:        2.7-1                conda-forge
    gettext:         0.19.8.1-0           conda-forge
    glib:            2.51.4-0             conda-forge
    graphite2:       1.3.11-0             conda-forge
    gsl:             2.1-2                conda-forge
    harfbuzz:        1.4.3-0              conda-forge
    icu:             58.2-0               conda-forge
    jpeg:            9b-2                 conda-forge
    krb5:            1.14.6-0             conda-forge
    libffi:          3.2.1-3              conda-forge
    libgcc:          7.2.0-h69d50b8_2
    libgcc-ng:       7.2.0-hdf63c60_3
    libiconv:        1.15-0               conda-forge
    libpng:          1.6.28-1             conda-forge
    libssh2:         1.8.0-1              conda-forge
    libstdcxx-ng:    7.2.0-hdf63c60_3
    libtiff:         4.0.7-0              conda-forge
    libxml2:         2.9.5-0              conda-forge
    ncurses:         5.9-10               conda-forge
    openssl:         1.0.2o-0             conda-forge
    pango:           1.40.4-0             conda-forge
    pcre:            8.41-1               conda-forge
    pixman:          0.34.0-1             conda-forge
    r-assertthat:    0.2.0-r3.3.2_0       conda-forge
    r-backports:     1.1.2-r3.3.2_0       conda-forge
    r-base:          3.3.2-5              conda-forge
    r-base64url:     1.3-r341h14c3975_0   local
    r-batchtools:    0.9.8-r341h14c3975_0 local
    r-brew:          1.0_6-r3.3.2_0       conda-forge
    r-checkmate:     1.8.5-r341h14c3975_0 local
    r-data.table:    1.10.4-r3.3.2_0      bioconda
    r-digest:        0.6.12-r3.3.2_0      bioconda
    r-magrittr:      1.5-r3.3.2_0         conda-forge
    r-prettyunits:   1.0.2-r3.3.2_0       bioconda
    r-progress:      1.0.2-r3.3.2_0       bioconda
    r-r6:            2.2.2-r3.3.2_0       conda-forge
    r-rappdirs:      0.3-r3.3.2_0         bioconda
    r-stringi:       1.1.7-r3.3.2_1       conda-forge
    r-withr:         2.1.1-r3.3.2_0       conda-forge
    readline:        6.2-0                conda-forge
    tk:              8.5.19-2             conda-forge
    xz:              5.2.3-0              conda-forge
    zlib:            1.2.8-3              conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/r-batchtools_1525026363975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/R -e 'library('\''batchtools'\'')'

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library('batchtools')
Error in library("batchtools") : there is no package called ‘batchtools’
Execution halted
Tests failed for r-batchtools-0.9.8-r341h14c3975_0.tar.bz2 - moving package to /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/broken
WARNING:conda_build.build:Tests failed for r-batchtools-0.9.8-r341h14c3975_0.tar.bz2 - moving package to /ebio/abt3_projects/software/dev/miniconda3_dev/conda-bld/broken
removing: r-batchtools-0.9.8-r341h14c3975_0.tar.bz2
TESTS FAILED: r-batchtools-0.9.8-r341h14c3975_0.tar.bz2
```

According to the package plan, `r-batchtools` is installed in the conda environment, but the simple test of `library('batchtools')` fails, and there doesn't appear to be any indication on why. 

Maybe it's something dumb that I'm just not seeing, but I can't figure it out based on the error reported during the build. Any ideas?

**Comment by isuruf** [comment]
Your locally built packages are built for r=3.4.1, while you are installing them on a r=3.3.2 environment.

**Comment by bgruening** [comment]
It seems you are mixing bioconda and conda-forge packages and your R version is quite old.
Please submit the PRs I'm confident this solves the problem at least for R3.4.1 :)

**Comment by jakirkham** [comment]
There's an update PR ( https://github.com/conda-forge/r-checkmate-feedstock/pull/1 ) for `r-checkmate`, which was recently fixed. That may help.

**Comment by jakirkham** [comment]
Added in PR ( https://github.com/conda-forge/staged-recipes/pull/6227 ). Closing this out.
