### ISSUE TITLE
Feedstocking is failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/staged-recipes#619]
Has been happening for the last 22-hours. Here is the [log]( https://travis-ci.org/conda-forge/staged-recipes/jobs/130203558#L289-L319 ) from the most recent failure. Traceback also shown below.

```
Repository created, please edit conda-forge.yml to configure the upload channels
and afterwards call 'conda smithy register-github'
fatal: Cannot update paths and switch to branch 'master' at the same time.
Did you intend to checkout 'upstream_with_token/master' which can not be resolved as commit?
Switched to a new branch 'master'
CI Summary for conda-forge/lua-5.1-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
Traceback (most recent call last):
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 156, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 166, in add_project_to_travis
    raise RuntimeError(msg.format(user))
RuntimeError: Unable to register the repo on Travis
(Is it down? Is the "conda-forge" name spelt correctly? [note: case sensitive])
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.10.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 228, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 167, in __call__
    print(e.message)
AttributeError: 'RuntimeError' object has no attribute 'message'
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 121, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp8xm756kl__feedstocks/lua-5.1-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
cc @pelson @ocefpaf

**Comment by pelson** [comment]
Agreed. I have been seeing this too. I'll investigate now.

**Comment by pelson** [comment]
Is this the `lua-5.1` feedstock. I wonder if we have seen a package with a period in the name before?

**Comment by pelson** [comment]
I have tried moving the `lua-5.1` directory to `lua`: https://github.com/conda-forge/staged-recipes/commit/a99129149c65b6eddc8bf310fc155db054cd72e3

**Comment by pelson** [comment]
😉  - https://travis-ci.org/conda-forge/staged-recipes/jobs/130348006.
We need to fix this in conda-smithy ideally, but for now, we should avoid folder names with `.` in them.

@jakirkham - can I ask you to raise the issue on conda-smithy?

**Comment by jakirkham** [comment]
> ...for now, we should avoid folder names with `.` in them.

Yet again a small punctuation mark bring conda-forge to its knees. 😜

> I have tried moving the `lua-5.1` directory to `lua`...

Yeah, that probably should have been changed beforehand.

> ...can I ask you to raise the issue on conda-smithy?

Yep, see this issue ( https://github.com/conda-forge/conda-smithy/issues/171 ).
