### ISSUE TITLE
a valid channel must contain a `noarch/repodata.json`

### ISSUE THREAD

**Issue by guyer** [conda-forge/staged-recipes#6621]
While attempting to respond to a reviewer comment for my fltk recipe submission (#6587), I got the following error. What to do?

```
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 440, in fetch_repodata_remote_request
    resp.raise_for_status()
  File "C:\Miniconda36-x64\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: None for url: file:///C:/Miniconda36-x64/conda-bld/noarch/repodata.json
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".ci_support\build_all.py", line 83, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 35, in build_all
    index = conda_build.conda_interface.get_index(channel_urls=channel_urls)
  File "C:\Miniconda36-x64\lib\site-packages\conda\common\io.py", line 46, in decorated
    return f(*args, **kwds)
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\index.py", line 65, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache)
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\index.py", line 83, in fetch_index
    index = collect_all_repodata_as_index(use_cache, channel_urls)
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 619, in collect_all_repodata_as_index
    index.update(sd.iter_dists_records())
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 175, in iter_dists_records
    self.load()
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 149, in load
    _internal_state = self._load()
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 227, in _load
    mod_etag_headers.get('_mod'))
  File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 571, in fetch_repodata_remote_request
    caused_by=e)
conda.exceptions.CondaHTTPError: HTTP 404 CONNECTION FAILED for url <file:///C:/Miniconda36-x64/conda-bld/noarch/repodata.json>
Elapsed: 00:00.000120
The remote server could not find the noarch directory for the
requested channel with url: file:///C:/Miniconda36-x64/conda-bld
As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
You will need to adjust your conda configuration to proceed.
```

**Comment by hajapy** [comment]
Seeing the same issue on this very simple recipe: https://github.com/conda-forge/staged-recipes/pull/6623

**Comment by guyer** [comment]
Thanks for following up. A fix for conda/conda-build#3114 has now been merged. 

Do I need to do anything to rebuild my pull requests once conda-forge's conda-build is updated?

**Comment by marcelotrevisani** [comment]
That it's not fixed yet, sorry  :(

I opened a PR to do an work around for that, waiting to another maintainer to review it, just to be sure that everything is ok

**Comment by marcelotrevisani** [comment]
That is fixed for now. So, I'm closing this issue. Thanks!
