### ISSUE TITLE
AppVeyor and Travis crash on init

### ISSUE THREAD

**Issue by crusaderky** [conda-forge/staged-recipes#7498]
I submitted two new recipes, https://github.com/conda-forge/staged-recipes/pull/7496 and https://github.com/conda-forge/staged-recipes/pull/7497.

They both crash before the recipe itself is even parsed.
I verified that my branch is identical to master with the only exception of the new file for the recipe.

Travis error message:

```
Configuring conda.
Missing CONDA_BUILD_SYSROOT: /Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
```

AppVeyor error message:

```
appveyor-retry conda.exe update --yes --quiet conda
Solving environment: ...working... failed
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "C:\Miniconda36-x64\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda36-x64\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\Miniconda36-x64\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Miniconda36-x64\lib\site-packages\conda\cli\main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "C:\Miniconda36-x64\lib\site-packages\conda\cli\install.py", line 235, in install
        force_reinstall=context.force,
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\solve.py", line 505, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\solve.py", line 438, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\solve.py", line 179, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\solve.py", line 560, in _prepare
        self.subdirs, prepared_specs)
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 94, in query
        self.load()
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 148, in load
        _internal_state = self._load()
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 235, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "C:\Miniconda36-x64\lib\site-packages\conda\core\subdir_data.py", line 353, in _process_raw_repodata_str
        package_record = PackageRecord(**info)
      File "C:\Miniconda36-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Miniconda36-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 736, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Miniconda36-x64\lib\site-packages\conda\_vendor\auxlib\entity.py", line 427, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
      File "C:\Miniconda36-x64\lib\site-packages\conda\models\records.py", line 102, in box
        val = tuple(f for f in (ff.strip() for ff in val) if f)
    TypeError: 'NoneType' object is not iterable
`$ C:\Miniconda36-x64\Scripts\conda update --yes --quiet conda`
  environment variables:
           APR_ICONV_PATH=C:\Program Files (x86)\Subversion\iconv
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Miniconda36-x64\Scripts\conda.exe
       CONDA_INSTALL_LOCN=C:\Miniconda36-x64
             CONDA_PREFIX=C:\Miniconda36-x64
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Miniconda36-x64\python.exe
               CONDA_ROOT=C:\Miniconda36-x64
              CONDA_SHLVL=1
             GIT_LFS_PATH=C:\Program Files\Git LFS
                 HOMEPATH=\Users\appveyor
                     PATH=C:\Miniconda36-x64;C:\Miniconda36-x64\Library\mingw-w64\bin;C:\Minicon
                          da36-x64\Library\usr\bin;C:\Miniconda36-x64\Library\bin;C:\Miniconda36
                          -x64\Scripts;C:\Miniconda36-x64\bin;C:\Program Files (x86)\Microsoft S
                          DKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C
                          :\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShe
                          ll\v1.0\;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web
                          Platform Installer\;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program
                          Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program
                          Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\120\Tools\Binn\ManagementStudio\;C:\Tools\WebDriver;C:\Program
                          Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Program Files
                          (x86)\Microsoft Visual Studio
                          12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft S
                          DKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:
                          \Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files
                          (x86)\CMake\bin;C:\go\bin;C:\Program
                          Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program
                          Files (x86)\iojs;C:\Program Files\iojs;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files
                          (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft
                          Visual Studio
                          14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program
                          Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL
                          Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL
                          Server\120\DTS\Binn\;C:\Program Files
                          (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program
                          Files\Mercurial\;C:\Program Files\dotnet\;C:\Tools\curl\bin;C:\Program
                          Files\Amazon\AWSCLI\;C:\Program Files (x86)\Microsoft SQL
                          Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 14
                          .0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Tools\vcpkg;C:\Pr
                          ogram Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program
                          Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\140\DTS\Binn\;C:\Program Files\erl9.2\bin;C:\Program Files
                          (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Git\cmd;C:\Program
                          Files\Git\usr\bin;C:\Program Files\Microsoft Service
                          Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service
                          Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program
                          Files\LLVM\bin;C:\Program Files
                          (x86)\Yarn\bin\;C:\Users\appveyor\AppData\Roaming\npm;C:\Program
                          Files\PowerShell\6\;C:\ProgramData\chocolatey\bin;C:\Program Files (x8
                          6)\nodejs\;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\L
                          ocal\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program
                          Files\AppVeyor\BuildAgent\
             PSMODULEPATH=C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Users\appveyo
                          r\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShe
                          ll\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Progr
                          am Files (x86)\Microsoft SQL
                          Server\110\Tools\PowerShell\Modules;C:\Program Files (x86)\Microsoft
                          SQL Server\120\Tools\PowerShell\Modules;C:\Program
                          Files\AppVeyor\BuildAgent\Modules;C:\Program Files (x86)\Microsoft SQL
                          Server\130\Tools\PowerShell\Modules;C:\Program Files (x86)\AWS
                          Tools\PowerShell;C:\Program Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager;C:\Program
                          Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ServiceManagement;C:\Program Files
                          (x86)\Microsoft SDKs\Azure\PowerShell\Storage;C:\Program Files
                          (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules;c:\Program
                          Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
     active environment : base
    active env location : C:\Miniconda36-x64
            shell level : 1
       user config file : C:\Users\appveyor\.condarc
 populated config files : C:\Users\appveyor\.condarc
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Miniconda36-x64  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
                          C:\Users\appveyor\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
Command "conda.exe update --yes --quiet conda" failed with exit code 1. Retrying 2 of 3
```

**Comment by crusaderky** [comment]
Existing projects crash with the same message, e.g. https://github.com/conda-forge/xarray-extras-feedstock/pull/9

**Comment by tkelman** [comment]
Try restarting the appveyor builds, it looks like that was a transient problem with outdated repodata on the mirror server. Travis may be something different related to their dropping support for an old xcode version?

**Comment by crusaderky** [comment]
@tkelman AppVeyor now works. I'm not sure I understood what you say there - from the failed log [1] I read:
[1] https://travis-ci.org/conda-forge/xarray-extras-feedstock/jobs/474729631
```
conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
...

Configuring conda.
Solving environment: ...working... done
## Package Plan ##
  environment location: /Users/travis/miniconda3
  added / updated specs: 
    - conda-forge-ci-setup=2

The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    ...
    conda-forge-ci-setup-2.0.2 |                0          19 KB  conda-forge
    ...
    ------------------------------------------------------------
                                           Total:        37.5 MB
The following NEW packages will be INSTALLED:
    ...
    conda-forge-ci-setup: 2.0.2-0               conda-forge
    ...

The following packages will be UPDATED:
...

The following packages will be DOWNGRADED:
...

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/setup_conda_rc", line 7, in <module>
    from conda_forge_ci_setup.build_utils import setup_conda_rc
ModuleNotFoundError: No module named 'conda_forge_ci_setup'
Missing CONDA_BUILD_SYSROOT: /Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
```
So what should I do?

**Comment by tkelman** [comment]
Wait until tomorrow I think. Mac is still installing an older version of conda-forge-ci-setup than it should be, and hopefully that can be fixed soon

**Comment by mariusvniekerk** [comment]
This has been fixed for a while.  Closing
