### ISSUE TITLE
azure-pipelines / staged-recipes (win_64 win) are failing the checks

### ISSUE THREAD

**Issue by mjscosta** [conda-forge/staged-recipes#7715]
Hi I've performed this https://github.com/conda-forge/staged-recipes/pull/7712, and azure-pipelines / staged-recipes (win_64 win) is failing, any ideia on this issue, is it blocking to publish the recipe ?

It seems not to be a localized issue with my pull request this one is having the same issue https://github.com/conda-forge/staged-recipes/pull/7713.

Thanks

**Comment by t-makaro** [comment]
Also affects #7717?

**Comment by kiwi0fruit** [comment]
```
2019-02-05T20:43:50.3089357Z Attempting to finalize metadata for mathjax
2019-02-05T20:43:50.4817650Z Traceback (most recent call last):
2019-02-05T20:43:50.4818251Z   File ".ci_support\build_all.py", line 130, in <module>
2019-02-05T20:43:50.4818978Z     build_all(args.recipes_dir, args.arch)
2019-02-05T20:43:50.4819355Z   File ".ci_support\build_all.py", line 68, in build_all
2019-02-05T20:43:50.4819728Z     build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
2019-02-05T20:43:50.4820055Z   File ".ci_support\build_all.py", line 120, in build_folders
2019-02-05T20:43:50.4820422Z     conda_build.api.build(list(d.keys()), config=get_config(arch, channel_urls))
2019-02-05T20:43:50.4820752Z   File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 208, in build
2019-02-05T20:43:50.4821096Z     notest=notest, need_source_download=need_source_download, variants=variants)
2019-02-05T20:43:50.4821423Z   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2314, in build_tree
2019-02-05T20:43:50.4821742Z     notest=notest,
2019-02-05T20:43:50.4822086Z   File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1324, in build
2019-02-05T20:43:50.4822433Z     output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
2019-02-05T20:43:50.4822757Z   File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 735, in expand_outputs
2019-02-05T20:43:50.4823112Z     for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
2019-02-05T20:43:50.4823439Z   File "C:\Miniconda\lib\site-packages\conda_build\metadata.py", line 2038, in get_output_metadata_set
2019-02-05T20:43:50.4826219Z     bypass_env_check=bypass_env_check)
2019-02-05T20:43:50.4826611Z   File "C:\Miniconda\lib\site-packages\conda_build\metadata.py", line 721, in finalize_outputs_pass
2019-02-05T20:43:50.4826984Z     permit_unsatisfiable_variants=permit_unsatisfiable_variants)
2019-02-05T20:43:50.4827380Z   File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 509, in finalize_metadata
2019-02-05T20:43:50.4827745Z     exclude_pattern)
2019-02-05T20:43:50.4828133Z   File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 371, in add_upstream_pins
2019-02-05T20:43:50.4828603Z     permit_unsatisfiable_variants, exclude_pattern)
2019-02-05T20:43:50.4829078Z   File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 359, in _read_upstream_pin_files
2019-02-05T20:43:50.4829461Z     permit_unsatisfiable_variants=permit_unsatisfiable_variants)
2019-02-05T20:43:50.4829907Z   File "C:\Miniconda\lib\site-packages\conda_build\render.py", line 143, in get_env_dependencies
2019-02-05T20:43:50.4830226Z     channel_urls=tuple(m.config.channel_urls))
2019-02-05T20:43:50.4830569Z   File "C:\Miniconda\lib\site-packages\conda_build\environ.py", line 738, in get_install_actions
2019-02-05T20:43:50.4830892Z     locking=locking, timeout=timeout)
2019-02-05T20:43:50.4831233Z   File "C:\Miniconda\lib\site-packages\conda_build\index.py", line 241, in get_build_index
2019-02-05T20:43:50.4831550Z     platform=subdir)
2019-02-05T20:43:50.4831871Z   File "C:\Miniconda\lib\site-packages\conda\exports.py", line 243, in get_index
2019-02-05T20:43:50.4832237Z     index = _get_index(channel_urls, prepend, platform, use_local, use_cache, unknown, prefix)
2019-02-05T20:43:50.4832562Z   File "C:\Miniconda\lib\site-packages\conda\common\io.py", line 85, in decorated
2019-02-05T20:43:50.4833442Z     return f(*args, **kwds)
2019-02-05T20:43:50.4834225Z   File "C:\Miniconda\lib\site-packages\conda\core\index.py", line 58, in get_index
2019-02-05T20:43:50.4834679Z     index = fetch_index(channel_urls, use_cache=use_cache)
2019-02-05T20:43:50.4835075Z   File "C:\Miniconda\lib\site-packages\conda\core\index.py", line 73, in fetch_index
2019-02-05T20:43:50.4835440Z     sd = SubdirData(Channel(url))
2019-02-05T20:43:50.4835804Z   File "C:\Miniconda\lib\site-packages\conda\core\subdir_data.py", line 60, in __call__
2019-02-05T20:43:50.4836187Z     assert channel.subdir
2019-02-05T20:43:50.4836544Z AssertionError
2019-02-05T20:43:51.4576698Z ##[error]Cmd.exe exited with code '1'.
2019-02-05T20:43:51.4973132Z ##[section]Finishing: Build recipe (maybe vs2008)
```

**Comment by kiwi0fruit** [comment]
@conda-forge/core, please help.

**Comment by scopatz** [comment]
The azure builds can be ignored for now

**Comment by kiwi0fruit** [comment]
Thanks!

**Comment by ajtritt** [comment]
@scopatz  how does one ignore a failing test? from everything I can see, the PR gets automatically merged when all tests pass.

**Comment by scopatz** [comment]
PRs are not getting automatically merged. That's odd

**Comment by chrisburr** [comment]
This should be fixed now for new builds.
