### ISSUE TITLE
Travis-CI failure on master

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/staged-recipes#85]
@pelson is this related to the latest `conda-smithy`?

See https://travis-ci.org/conda-forge/staged-recipes/jobs/115055485

```
Repository created, please edit conda-forge.yml to configure the upload channels
and afterwards call 'conda smithy register-github'
usage: a tool to help create, administer and manage feedstocks.
       [-h]
       {init,register-github,register-ci,regenerate,recipe-lint,rerender} ...
a tool to help create, administer and manage feedstocks.: error: invalid choice: 'github-create' (choose from 'init', 'register-github', 'register-ci', 'regenerate', 'recipe-lint', 'rerender')
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 118, in <module>
    subprocess.check_call(['conda', 'smithy', 'github-create', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'github-create', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp_pPzpc__feedstocks/autoconf-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 2
```

**Comment by pelson** [comment]
Ah, yes. I'd forgotten about this. @JanSchulz wanted to rename the subcommand.
The change will need to happen in https://github.com/conda-forge/staged-recipes/blob/7e70cff1999503f9ed04e8cbaabe8be60d1d1d1e/.CI/create_feedstocks.py#L118

**Comment by ocefpaf** [comment]
I can do that if you are not already on it.

**Comment by pelson** [comment]
> I can do that if you are not already on it.

Super. Thanks @ocefpaf

**Comment by pelson** [comment]
Doh. Wrong button! :smile: :fist:

**Comment by ocefpaf** [comment]
I am re-opening this because #88 and #86 did not do the trick. See https://travis-ci.org/conda-forge/staged-recipes/jobs/115119743

```
Repository created, please edit conda-forge.yml to configure the upload channels
and afterwards call 'conda smithy register-github'
fatal: Cannot update paths and switch to branch 'master' at the same time.
Did you intend to checkout 'upstream_with_token/master' which can not be resolved as commit?
Switched to a new branch 'master'
usage: a tool to help create, administer and manage feedstocks.
       [-h]
       {init,register-github,register-ci,regenerate,recipe-lint,rerender} ...
a tool to help create, administer and manage feedstocks.: error: unrecognized arguments: /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpRktoK8__feedstocks/autoconf-feedstock
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 123, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpRktoK8__feedstocks/autoconf-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 2
```

**Comment by ocefpaf** [comment]
Maybe that is because that package feedstock is already registered.

**Comment by ocefpaf** [comment]
OK... I give up! #89,  #88 and #86 did not solve the problem. (Hopefully I did not make things worse :pray:)

The problem now is

```
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-build-all", line 9, in <module>
    load_entry_point('conda-build-all==0.9.0', 'console_scripts', 'conda-build-all')()
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_build_all/cli.py", line 85, in main
    b.main()
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_build_all/builder.py", line 207, in main
    built_dist_location = self.build(meta)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_build_all/builder.py", line 164, in build
    return bldpkg_path(build.build(meta.meta))
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_build_all/build.py", line 34, in build
    build_module.test(meta, **kwd)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 571, in test
    create_env(config.test_prefix, specs)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 309, in create_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 297, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/Users/travis/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 378, in download
    chunk  = resp.raw.read(2**14)
ValueError: I/O operation on closed file
```

**Comment by jjhelmus** [comment]
There were some pretty bad behaviors of conda 4.0.3 release which may be related to this.  What version of conda was installed?

**Comment by ocefpaf** [comment]
> There were some pretty bad behaviors of conda 4.0.3 release which may be related to this.

I guess so as re-starting it today solved the problem.

> What version of conda was installed?

We always update to the latest. That sounds like a bad strategy, but conda (and conda-build) has always been a moving target and it is the only way to keep up.

**Comment by jjhelmus** [comment]
I think using the latest conda is still a good idea.  Yesterday's 4.0.3 release was just a case of a bad bug making in into a release and the Continuum folks pulled the release and provided a fix extremely quickly.  Unfortunately, it took a bit for 4.0.3 to make it out of the various cache and so many builds were broken during this period.

**Comment by ocefpaf** [comment]
Re-opening it again :unamused: 

`register-ci` is not working properly. I guess this is still realted to @JanSchulz changes to conda-smithy, but I cannot see any obvious places to fix.

**Comment by ocefpaf** [comment]
#94 seems to be fix this.

**Comment by jjhelmus** [comment]
Nice work @ocefpaf
