### ISSUE TITLE
Package builds fail with recent conda/conda-build releases

### ISSUE THREAD

**Issue by xhochy** [conda-forge/staged-recipes#8798]
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=49420&view=logs

Traceback:

```
+ python /home/conda/.ci_support/build_all.py /home/conda/conda-recipes
Building pgcopy with conda-forge/label/main
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 131, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 94, in build_folders
    conda_resolve = conda_build.conda_interface.Resolve(index)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 116, in __init__
    self._system_precs = {_ for _ in index if _.package_type == PackageType.VIRTUAL_SYSTEM}
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 116, in <setcomp>
    self._system_precs = {_ for _ in index if _.package_type == PackageType.VIRTUAL_SYSTEM}
AttributeError: 'Dist' object has no attribute 'package_type'
```

**Comment by xhochy** [comment]
Same error as in https://github.com/conda-forge/conda-smithy/issues/1105

**Comment by xhochy** [comment]
This has been resolved
