### ISSUE TITLE
Recipes don't get removed after conversion

### ISSUE THREAD

**Issue by dbast** [conda-forge/staged-recipes#8976]
The conversion pipeline currently gets stuck with:
```
[master 8068600] Re-render the feedstock after CI registration.
 1 file changed, 5 insertions(+), 5 deletions(-)
 rewrite conda-forge.yml (84%)
rm 'recipes/r-rticles/bld.bat'
rm 'recipes/r-rticles/build.sh'
rm 'recipes/r-rticles/meta.yaml'
Saved working directory and index state WIP on master: 1278e9d3 Merge pull request #8783 from gpilab/gpi_core
HEAD is now at 1278e9d3 Merge pull request #8783 from gpilab/gpi_core
Created autostash: 532160bc
HEAD is now at 1278e9d3 Merge pull request #8783 from gpilab/gpi_core
Cannot rebase: You have unstaged changes.
Please commit or stash them.
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 204, in <module>
    subprocess.check_call(['git', 'rebase', '--autostash'])
  File "/home/travis/miniconda/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'rebase', '--autostash']' returned non-zero exit status 1.
+++python .travis_scripts/trigger_travis_build.py conda-forge/staged-recipes
b'{\n  "@type": "error",\n  "error_type": "request_limit_reached",\n  "error_message": "request limit reached for resource",\n  "repository": {\n    "@type": "repository",\n    "@href": "/repo/5842170",\n    "@representation": "minimal",\n    "id": 5842170,\n    "name": "staged-recipes",\n    "slug": "conda-forge/staged-recipes"\n  },\n  "max_requests": 10,\n  "per_seconds": 3600\n}'
Traceback (most recent call last):
  File ".travis_scripts/trigger_travis_build.py", line 54, in <module>
    sys.exit(main(sys.argv))
  File ".travis_scripts/trigger_travis_build.py", line 47, in main
    rebuild_travis(args.slug)
  File ".travis_scripts/trigger_travis_build.py", line 38, in rebuild_travis
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.travis-ci.org/repo/conda-forge%2Fstaged-recipes/requests
```

Several recipes were already converted and now receive rerender changes, as removing does not kick in:
* https://github.com/conda-forge/gpi_core-feedstock/commits/master
* https://github.com/conda-forge/r-rticles-feedstock/commits/master

How to resolve that? Manually removing the converted recipes?

**Comment by dbast** [comment]
Solved via https://github.com/conda-forge/staged-recipes/pull/8979
