### ISSUE TITLE
Circular dependency with bazel error

### ISSUE THREAD

**Issue by mwilson8** [conda-forge/staged-recipes#9972]
I'm attempting to add google-differential-privacy to the forge, which is built with bazel.. After downloading the source and running the bazel build command they specify, it hard crashes with this error 
``` ERROR: circular symlinks detected
[start of symlink cycle]
/home/conda/staged-recipes/build_artifacts/google-differential-privacy_1571944966203/_build_env/share/terminfo/N/NCR260VT300WPP
[end of symlink cycle]
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

INFO: Elapsed time: 33.934s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (48 packages loaded, 1191 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
FAILED: Build did NOT complete successfully (48 packages loaded, 1191 targets configured)
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 134, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 124, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2339, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1487, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 399, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 379, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/staged-recipes/build_artifacts/google-differential-privacy_1571944966203/work/conda_build.sh']' returned non-zero exit status 37.
```

Which seems that it doesn't like symlinks to places inside the source dir.. Is this error caused because of conda? If so is there a way to solve? 
Should I ping the core team for this?

**Comment by jakirkham** [comment]
Are you able to make a PR? It’s probably easier to engage with the problem in a PR than an issue.

**Comment by mwilson8** [comment]
https://github.com/conda-forge/staged-recipes/pull/9975
